name: Generate and Commit Report

on: push

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run your script to generate the report
        run: |
          # Your script to generate the CSV report goes here
          echo "name,value" > report.csv
          echo "example,123" >> report.csv

      - name: Configure git for commit
        run: |
          git config user.name "Kayode Yusuf"
          git config user.email "kayode40@github.com"

      - name: Commit changes
        run: |
          git add *.csv
          git commit -m "Adding file to repo" || echo "No changes to commit"

      - name: Rebase on top of the latest master
        run: |
          git fetch origin main
          git rebase origin/main --strategy-option=ours

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
