name: Wofkflow A

on: [push]

env:
  actions_repo_version: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@$actions_repo_version
        with:
          ref: 'main'
      - name: Run Test A
        run: echo "This job is on main"
